# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies without running prepare scripts
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy source and build
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

# Runtime image
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy built files and production deps
COPY package.json package-lock.json ./
RUN npm install --only=production --ignore-scripts
COPY --from=builder /app/build ./build

# Default command
CMD ["node", "build/index.js"]
